sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

before_install:
  - git clone https://github.com/hansnow/fund-calc
  - npm install
  - npm run build
  - mkdir -p fund-calc/frontend
  - cp -R dist/ fund-calc/frontend && cd fund-calc
  - docker build -t hansnow/fund-calc .
  - docker run -d --name fund hansnow/fund-calc
  - docker ps -a

script:
  - echo 'finish'

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push hansnow/fund-calc
